project:
  type: website

website:
  title: "  "
  navbar:
    background: "#235440"
    search: true
    left:
      - text: Home
        file: index.qmd
      - text: Resources
        menu:
        - text: TikTok Trends
          file: tt-trends.qmd
    right:
      - icon: envelope
        aria-label: envelope
        href: mailto:mrober40@fitchburgstate.edu
      - icon: github
        aria-label: github
        href: https://github.com/mroberts1
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/mroberts_fsu
format:
  html:
    toc: true
    toc-depth: 3
    toc-location: right
    toc-title: '   '
    theme:
      light: ember.scss
      dark: [ember.scss, vapor]
    css: custom.scss
    self-contained: true
    grid:
        margin-width: 350px
    linestretch: 1.5
    smooth-scroll: true
    linkcolor: "#235440"
    link-external-newwindow: true
  typst:
    papersize: us-letter
    mainfont: "Source Sans Pro"
    fontsize: 14pt
    margin:
      x: 1.25in
      y: 1.25in
fig-responsive: true
image-alt: " "
execute:
  echo: false
reference-location: margin
citation-location: margin
editor: visual
