project:
  type: website
  resources:
    - "pdf/*.pdf"

website:
  title: "  "
  navbar:
    background: "#235440"
    search: true
    left:
      - text: Home
        file: index.qmd
      - text: Lectures
        menu:
        - text: W1 Interpassive Aggressive
          file: /lectures/w1-interpassive.qmd
        - text: W2 Digital Swarms
          file: /lectures/w2-digital-swarms.qmd
        - text: W3 Selfies
          file: /lectures/w3-selfies.qmd
      - text: Resources
        menu:
        - text: Digital Gardens
          file: /resources/digital-gardens.qmd
        - text: Mastodon
          file: /resources/mastodon.qmd
        - text: TikTok Trends
          file: /resources/tt-trends.qmd
    right:
      - icon: envelope
        aria-label: envelope
        href: mailto:mrober40@fitchburgstate.edu
      - icon: github
        aria-label: github
        href: https://github.com/mroberts1
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/mroberts_fsu
format:
  html:
    toc: true
    toc-depth: 2
    toc-location: left
    toc-title: '   '
    theme:
      light: ember.scss
      dark: [ember.scss, slate]
    css: custom.scss
    self-contained: true
    grid:
        margin-width: 350px
    linestretch: 1.5
    fontsize: 1.1em
    smooth-scroll: true
    linkcolor: "#235440"
    link-external-newwindow: true
  # typst:
    # papersize: us-letter
    #mainfont: "Source Sans"
    #fontsize: 14pt
    #margin:
     # x: 1.25in
      #y: 1.25in
fig-responsive: true
image-alt: " "
execute:
  freeze: auto
reference-location: margin
citation-location: margin
editor: visual
