---
title: '  '
---

```{r}
#| label: load-packages
#| include: false

library(tidyverse)
library(palmerpenguins)
```

#### TikTok Trends

[Butter boards](https://www.nytimes.com/2022/09/30/dining/butter-boards.html), [sexy water](https://www.popsugar.com/fitness/sexy-water-49347542), [blueberry milk nails](https://www.realsimple.com/blueberry-milk-nails-7562399), [unexpected red](https://www.nytimes.com/2024/02/16/style/what-is-unexpected-red.html), [lucky girl syndrome](https://www.harpersbazaar.com/uk/beauty/mind-body/a42590695/lucky-girl-syndrome/), [first-time-cool syndrome](https://www.vox.com/culture/24062406/tiktok-trends-slang-terms-coining), [bed rotting](https://www.nytimes.com/2024/02/17/well/bed-rotting-hurkle-durkle.html), [75 soft](https://www.glamourmagazine.co.uk/article/75-soft-challenge-tiktok), [75 cozy](https://afterschool.substack.com/p/75-cozy-and-cold-fish), [bookshelf wealth](https://www.nytimes.com/2024/01/15/style/do-you-have-bookshelf-wealth.html), [loud budgeting](https://www.nytimes.com/interactive/2024/03/22/business/what-is-loud-budgeting.html), [broccoli freckles](https://nypost.com/2024/03/08/lifestyle/gen-z-millennials-are-obsessed-with-broccoli-freckles-trend/), [strawberry makeup](https://www.elle.com/beauty/makeup-skin-care/a44506818/hailey-bieber-strawberry-makeup-how-to/), [glazed donut skin](https://www.glamour.com/story/glazed-donut-skin-trend), [latte makeup](https://www.realsimple.com/latte-makeup-7565436), [cowboy copper hair](https://www.glamour.com/story/cowboy-copper-hair-trend), [old money blonde](https://www.elle.com/uk/beauty/hair/a46900482/old-money-blonde-hair/), [expensive brunette](https://www.instyle.com/hair/hair-color/expensive-brunette-hair-trend), [orange peel theory](https://www.nytimes.com/2023/11/30/style/orange-peel-theory.html), [quiet luxury](https://www.nytimes.com/2023/07/22/style/quiet-luxury-wealth-status.html), [stealth wealth](https://www.theatlantic.com/technology/archive/2023/05/stealth-wealth-fashion-trend-succession-tiktok/674065/), [tomato girl summer](https://www.teenvogue.com/story/tiktok-tomato-girl-summer-aesthetic-trend-explained), [indie sleaze](https://www.vice.com/en/article/wxjnnm/vice-guide-indie-sleaze), [coquette](https://www.nytimes.com/2023/09/26/style/ribbons-bows-nyfw-tiktok.html), [looksmaxxing](https://www.nytimes.com/2023/11/06/style/looksmaxxing-tik-tok-dillon-latham.html), [male perms](https://www.nytimes.com/2023/04/29/style/korean-men-perm.html), [vanilla girl](https://www.today.com/life/vanilla-girl-aesthetic-tiktok-trend-rcna73817), [clean girl](https://www.byrdie.com/clean-girl-aesthetic-critique-6744031), [soft girl](https://www.glamourmagazine.co.uk/article/soft-girl-aesthetic), [coastal grandma](https://www.today.com/shop/coastal-grandmother-style-t253673), [coastal cowgirl](https://people.com/coastal-cowgirl-fashion-trend-everything-to-know-7503901), [low-high visual weight makeup](https://mashable.com/article/what-is-visual-weight-face-makeup-tiktok), [sleepy-girl mocktails](https://www.nytimes.com/2024/01/17/well/live/sleepy-girl-mocktail-cherry-magnesium.html), [fluffy coffee](https://www.today.com/food/what-whipped-coffee-tiktok-trend-t176307), [shrimp tree](https://www.eater.com/24007037/vintage-1970s-shrimp-christmas-tree-centerpiece-trend), [girl math](https://www.cbsnews.com/baltimore/news/what-is-girl-math-tiktok-budgeting/), [girl dinner](https://www.nytimes.com/2023/07/08/style/girl-dinner.html), [mob wife](https://www.nytimes.com/2024/01/28/style/mob-wife-aesthetic-trend.html), [clowncore](https://harpersbazaar.com.au/clowncore-fashion-trend/), [balletcore](https://www.whowhatwear.com/balletcore-trend), [Barbiecore](https://people.com/style/barbiecore-fashion-trend-everything-to-know/), [royalcore](https://www.housebeautiful.com/uk/decorate/looks/a37979440/royalcore/), [corecore](https://time.com/6248637/corecore-tiktok-aesthetic/)

---Source: Madison Malone Kircher, "[It Spawned a Zillion Trends. Or at Least, 'Trends'](https://www.nytimes.com/interactive/2024/04/18/business/media/tiktok-ban-american-culture.html)" (*New York Times*, 19 April 2024).

***  
