---
title: '  '
---

```{r}
#| label: load-packages
#| include: false

library(tidyverse)
library(palmerpenguins)
```

#### W4: Fangirls

I hope you enjoyed Nancy Baym's account of how social media have transformed the relationship of musicians to their audiences, and to their fans in particular.

I wanted to start with a few questions, and then make some observations about what appear to be some of the blind spots in Baym's account, perhaps because of the warp speed at which social media platforms themselves are constantly evolving.

Some questions first. Since we're all, in varying degrees, music fans, I'm wondering how any of the relationships between musicians and fans that Baym describes connect to your own experience. Do you follow closely the social media accounts of artists and/or bands that you're a fan of? Have you yourself had any direct personal interactions on social media platforms with musicians that you're a fan of? Have you encountered musicians after concerts that you've attended, at the merchandise table or elsewhere? If so, did your experience correspond with Baym's account, in terms of the ritualistic nature of the interaction or the specific boundaries in live venues?

With regard to blind spots, the most obvious elephant in the room is TikTok, although to be fair the book was researched and written several years before the platform arrived. So my question here is quite specific: how far do you think the "relational affordances," in terms of the new ways for musicians and fans to interact with one another on SM platforms, that Baym describes in the case of MySpace, Facebook, and Twitter, have carried over to TikTok? Or have the platform's own particular affordances further transformed the relationship between musicians and their audiences? If so, how? What are the particular challenges that an SM platform like TikTok poses to musicians seeking to "sneak into the everyday lives" of their audiences, and how differently are they going about doing so?

One other blind spot of Baym's discussion that struck me was the absence from it of any consideration of a new musical generation that has emerged in recent years: the social media musician. As you'll have seen, Baym's book is exclusively concerned with musicians whose careers developed in generations that pre-date social media platforms, and who can thus be considered as "late adopters" (as opposed to "early adopters"), in that they and their managements have had to adapt as best they can to the new rules of the game. This older generation includes musicians such as Bruce Springsteen, Bill Bragg, REM, Roger O'Donnell of The Cure, and others.

However, as I'm sure many of you will also know, the past decade in particular has seen the emergence of many new musicians whose careers originate on social media platforms, particularly YouTube. Just a few examples:

-   [Andrew Hwang](https://www.youtube.com/@andrewhuang)
-   [Mylar Melodies](https://www.youtube.com/@mylarmelodies)
-   [Emily Hopkins](https://www.youtube.com/@emilyharpist)
-   [Josie Charlwood](https://www.youtube.com/@JosieCharlwoodmusic)
-   [Hainbach](https://www.youtube.com/@Hainbach)

Musicians like these differ from the generation that Baym discusses in that they belong to a younger generation (millennials, Gen-Z) and can be considered "social media natives" (to adapt the "digital natives" concept). Although they do perform live, YouTube is their primary distribution platform, in tandem with Soundcloud and Bandcamp (for direct sales to their fans). They are highly adept at managing their online musical persona, including via Instagram, Facebook, and/or Twitter.

While Baym's account of how "traditional" rock and other musicians are adapting to the new rules of the game of social media, it could be argued that we should be paying closer attention to how the current generation of social media musicians have been developing new kinds of musical personas, as well as new and more direct ways of building and maintaining their social media fanbase.

So I'm wondering what other, similar examples you can think of that exemplify this new category of the social media musician? Do you follow any such musicians yourself? If so, feel free to add links to them in the Discord discussion.

To tie the two strands of the preceding discussion together, is there now an emerging generation of TikTok musicians? Although I'm more familiar with YouTube musicians, this is pretty much unknown territory to me, so I'd be  interested in any examples that come to mind either of how established musicians are using TikTok, or upcoming ones are using it as a platform for their music. This would be a good complement to Baym's account of how today's SM platforms are transforming the relationship between a previous generation of musicians and their fanbases.

Lastly, if you're interested in the contemporary convergence between the music business and social media, check out music journalist Cherie Hu's website, which also hosts her newsletter, [Water & Music](https://www.waterandmusic.com/). I recommend scrolling down and having a look at the materials under the heading "Starter Packs."
